---
env: 'local-dev'

#the port used by the surrogeth deamon
surrogethPort: 8123
#external ip for surrogeth
surrogethIp: "127.0.0.1"

#define all the network the deamon will server
network:
    kovan:
        #The URL of the RPC of the network
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        #The chainId of the network
        chainId: 42
        #The private key path for the network in an array format ["key"]
        privateKeysPath: "kovanPrivateKeys.json"
        #the forwarder contract to interact with
        ForwarderRegistryERC20: "0xBB9C41E86A72580359dd4Bff1a574C19D861966a"
        #the list of token that are supported
        token:
            #the default token: eth
            eth:
                #the minimum fee, lower gain reject the transaction
                feeAmt: 0.001
            dai:
                #the address of the ERC20 token contract
                address: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
                #the number of decimals
                decimals: 20
                #the minimum fee in token, lower gain reject the transaction
                feeAmt: 2

    ganache:
        url: "http://localhost:8545"
        chainId: 1337
        privateKeysPath: "ganachePrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001
            tkn:
                address: 0x394BfB86641Bf8cA8A757a318499A580Cc1f26C6
                decimals: 18
                feeAmt: 1.9

    ropsten:
        url: "https://ropsten.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 3
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    arbitrum:
        url: "https://kovan4.arbitrum.io/rpc"
        chainId: 212984383488152
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    skale:
        url: "https://dev-testnet-v1-0.skalelabs.com"
        chainId: 344435
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001
