---
env: 'local-dev'

deployedAddresse: "../../../contracts/deployedAddresses.json"
surrogethPort: "8123"


network:
    kovan:
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 42
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001
            tkn:
                decimals: 18
                feeAmt: 2
            dai:
                deployedAddresse: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa'
                decimals: 18
                feeAmt: 2

    ganache:
        url: "http://localhost:8545"
        chainId: 1337
        privateKeysPath: "ganachePrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001
            tkn:
                decimals: 18
                feeAmt: 0.02
