---
env: 'local-dev'

surrogethPort: "8123"


network:
    kovan:
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 42
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    ganache:
        url: "http://localhost:8545"
        chainId: 1337
        privateKeysPath: "ganachePrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    ropsten:
        url: "https://ropsten.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 3
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    arbitrum:
        url: "https://kovan4.arbitrum.io/rpc"
        chainId: 212984383488152
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001

    skale:
        url: "https://dev-testnet-v1-0.skalelabs.com"
        chainId: 344435
        privateKeysPath: "kovanPrivateKeys.json"
        token:
            eth:
                feeAmt: 0.001
